version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network
    restart: unless-stopped

  config-server-ms:
    image: bnitinraj/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - 8080:8080
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - postgres_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image: bnitinraj/servicereg:latest
    container_name: servicereg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres_network

  companyms:
    image: bnitinraj/companyms:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - postgres_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: bnitinraj/jobms:latest
    container_name: job
    ports:
      - 8082:8082
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - postgres_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker



  reviewms:
    image: bnitinraj/reviewms:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
      - postgres_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    image: bnitinraj/gateway-ms:latest
    container_name: gateway
    ports:
      - 8084:8084
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - postgres_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_container
    ports:
      - "9411:9411"
    networks:
      - postgres_network
      - microservice-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" #rabbitmq port
      - "15672:15672" #rabbitmq management port
    networks:
      - postgres_network
      - microservice-network

networks:
  postgres_network:
    driver: bridge
  microservice-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
